FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
COPY ./*.sln ./

# Copy the main source project files
COPY /*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p /${file%.*}/ && mv $file /${file%.*}/; done

RUN dotnet restore

COPY . .
ENTRYPOINT ["dotnet", "test"]

